In [1]:
# Average departure delay

# For each airline per airport, what is the average departure delay?

# AIRLINE
# ORIGIN AIRPORT
# total number of flight
# Operated rate (% of flights that did not cancel)
# Delay rate (departure) --> exclude cancelled flight
# Average delay minutes (departure) --> exclude non-delay flight

import pandas as pd
import numpy as np

df_airports = pd.read_csv('./airports.csv')
df_airlines = pd.read_csv('./airlines.csv')
df_flights = pd.read_csv('./flights.csv')

df_output = df_flights.groupby(['AIRLINE','ORIGIN_AIRPORT']).agg({
  'FLIGHT_NUMBER':'count',
  'CANCELLED': lambda x: (x == 0).sum(),
  'DEPARTURE_DELAY': [lambda x: (x > 0).sum(), lambda x: x[x > 0].mean()]
})

df_output.columns = ['TOTAL_FLIGHTS', 'NON_CANCELLED_FLIGHTS', 'NUM_DELAYED_FLIGHTS', 'AVG_DEPARTURE_DELAY']

df_output['OPERATED_RATE_%'] = df_output['NON_CANCELLED_FLIGHTS'] / df_output['TOTAL_FLIGHTS']*100
df_output['DELAY_RATE_%'] = df_output['NUM_DELAYED_FLIGHTS'] / df_output['NON_CANCELLED_FLIGHTS']*100

df_output.loc[:, ['TOTAL_FLIGHTS', 'NON_CANCELLED_FLIGHTS', 
                  'NUM_DELAYED_FLIGHTS', 'OPERATED_RATE_%', 
                  'DELAY_RATE_%', 'AVG_DEPARTURE_DELAY'
                  ]]

/var/folders/1v/6y1hxnk974jd3n1dvc40c41h0000gn/T/ipykernel_40996/2498518775.py:17: DtypeWarning: Columns (7,8) have mixed types. Specify dtype option on import or set low_memory=False.
  df_flights = pd.read_csv('./flights.csv')

                        TOTAL_FLIGHTS  NON_CANCELLED_FLIGHTS  \
AIRLINE ORIGIN_AIRPORT
AA      10140                     174                    170
        10257                      80                     80
        10299                      32                     32
        10397                     917                    910
        10423                     786                    771
...                               ...                    ...
WN      SNA                     17197                  17047
        STL                     27753                  27445
        TPA                     25888                  25657
        TUL                      4098                   4067
        TUS                      4201                   4181

                        NUM_DELAYED_FLIGHTS  OPERATED_RATE_%  DELAY_RATE_%  \
AIRLINE ORIGIN_AIRPORT
AA      10140                            43        97.701149     25.294118
        10257                            17       100.000000     21.250000
        10299                             8       100.000000     25.000000
        10397                           239        99.236641     26.263736
        10423                           178        98.091603     23.086900
...                                     ...              ...           ...
WN      SNA                            8105        99.127755     47.545023
        STL                           12286        98.890210     44.765895
        TPA                           10430        99.107695     40.651674
        TUL                            1544        99.243533     37.964101
        TUS                            1484        99.523923     35.493901

                        AVG_DEPARTURE_DELAY
AIRLINE ORIGIN_AIRPORT
AA      10140                     43.209302
        10257                     27.764706
        10299                      8.125000
        10397                     22.991632
        10423                     42.050562
...                                     ...
WN      SNA                       20.307465
        STL                       28.778121
        TPA                       30.291083
        TUL                       30.478627
        TUS                       27.552561

[3437 rows x 6 columns]